# Generated by Django 5.1.6 on 2025-04-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_state',
            field=models.CharField(default='require_credentials', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
