# Generated by Django 5.1.6 on 2025-04-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_user_auth_state_user_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
